services:
  - type: web
    name: coach-pine
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OANDA_API_KEY
        value: 7aebce90504e63e822c57ef1fc470342-c08d4902fac33b484ee1585ffb8eab77
      - key: OANDA_ACCOUNT_ID
        value: 101-002-37655263-001
      - key: OPENAI_API_KEY
        value: srv-d4a5k8p5pdvs73e0k7lg
      - key: TELEGRAM_TOKEN
        value: 8476632235:AAHnCiD1SZiHwB-8Vp6musVQjqd41W3mIMg
      - key: TELEGRAM_CHAT_ID
        value: 8476632235
